version: '3.9'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MIGRATIONS_TABLE_NAME: "${MIGRATIONS_TABLE_NAME}"
      DB_TYPE: "${DB_TYPE}"
      DB_PORT: "${DB_PORT}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
      DB_HOST: postgres
      PORT: "${PORT}"
    networks:
      - rest-serivce
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./db/Dockerfile
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"
      PG_DATA: /var/lib/postgresql/data
    networks:
      - rest-serivce
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    restart: unless-stopped

networks:
  rest-serivce:
    name: rest-serivce
    driver: bridge

volumes:
  pgdata:
  app: